FROM node:20.15.1 as build

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY . ./

ENV NODE_ENV development
ENV PORT 3000

CMD ["yarn", "dev"]

EXPOSE 3000
